# Site settings
title: razzi.abuissa.net
email: razzi53@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://razzi.abuissa.net"
twitter_username: razzzzi
github_username: razzius
defaults:
  -
    scope:
      path: ""
    values:
      layout: base

# Build settings
markdown: kramdown
highlighter: pygments
