title: razzi.abuissa.net
email: razzi@abuissa.net
author: Razzi Abuissa
description: ""
url: "https://razzi.abuissa.net"
twitter_username: razzzzi
github_username: razzius
defaults:
  -
    scope:
      path: ""
    values:
      layout: base

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

terrible_vegan_description: Veganism, stories, and perspectives
