# Site settings
title: razzi.abuissa.net
email: razzi@abuissa.net
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://razzi.abuissa.net"
twitter_username: razzzzi
github_username: razzius
defaults:
  -
    scope:
      path: ""
    values:
      layout: base

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
